### PR TITLE
feat:update new-README and CREDITS

### PR DESCRIPTION
**Pull request by Rocksnake**
en：
- update README file below /development/languages/new
- I volunteered to take on the translation of the new languages module

zh：
- 更新 /development/languages/new: README.md
- 愿意承担new languages模块的翻译任务

### CODE REVIEW

**Comment by chuyao** [comment]
请把mac系统 .DS_Store文件忽略提交

**Comment by zhyChesterCheung** [comment]
LGTM

**Review by hanyuancheung — APPROVED** [review]
LGTM

**Review by hanyuancheung — APPROVED** [review]
LGTM

**Pull request merged**
